"""jobpack.py -- the COMPLETE job package for one part, as a single printable PDF. Pulls together
everything a mechanic needs to take to the bay: the part's identity (nomenclature/NSN + authoritative
PUBLOG data), the interchangeability/supersession warnings, the key dimensions & torque, the safety
cautions, the parts-to-order list, and the procedure steps -- all cited. One document, one print.

build(pkg) takes a plain data dict (the route gathers it from the existing indexes + PUBLOG) and returns
PDF bytes, so this module is pure and unit-testable. Degrades section-by-section: any missing piece is
simply omitted. Never a substitute for the manual -- it cites every page and says so."""

from __future__ import annotations
import io

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                    HRFlowable, ListFlowable, ListItem)
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    _OK = True
except Exception:                       # pragma: no cover
    _OK = False


def available() -> bool:
    return _OK


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H", parent=ss["Heading2"], textColor=colors.HexColor("#12325a"),
                          spaceBefore=10, spaceAfter=4, fontSize=12))
    ss.add(ParagraphStyle("Body", parent=ss["BodyText"], fontSize=9.5, leading=12.5))
    ss.add(ParagraphStyle("Small", parent=ss["BodyText"], fontSize=8, textColor=colors.HexColor("#555555"), leading=10))
    ss.add(ParagraphStyle("Warn", parent=ss["BodyText"], fontSize=9.5, textColor=colors.HexColor("#8a1c1c"), leading=12))
    return ss


def _esc(s):
    return (str(s) if s is not None else "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build(pkg: dict) -> bytes:
    """Render the complete job package. `pkg` keys (all optional except title):
       title, nsn, item_name, fsc_title, verdict{label,reason},
       supersession{status,aac_meaning,replaced_by[]}, dims[{type,value,unit,source}],
       torque[{value,context,page}], cautions[{kind,text}], parts[{nsn,uoc,cagec,note}],
       procedures[{kind,vehicle,page,tools[],steps[]}], figure_note, generated"""
    if not _OK:
        raise RuntimeError("reportlab not installed")
    ss = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch,
                            leftMargin=0.7 * inch, rightMargin=0.7 * inch, title="Job package")
    E = []
    title = _esc(pkg.get("title") or pkg.get("item_name") or pkg.get("nsn") or "Job package")
    E.append(Paragraph("Maintenance Job Package", ParagraphStyle("T", parent=ss["Title"], fontSize=17,
                       textColor=colors.HexColor("#12325a"))))
    sub = title
    if pkg.get("nsn"):
        sub += "  &bull;  NSN %s" % _esc(pkg["nsn"])
    if pkg.get("fsc_title"):
        sub += "  &bull;  %s" % _esc(pkg["fsc_title"])
    E.append(Paragraph(sub, ss["Body"]))
    E.append(Paragraph("Generated by THE VIEWER%s. Every value is cited to the manual page; verify torque, "
                       "sequence, and CAUTION/WARNING against the actual TM before working." %
                       (" &bull; " + _esc(pkg["generated"]) if pkg.get("generated") else ""), ss["Small"]))
    E.append(HRFlowable(width="100%", color=colors.HexColor("#12325a"), spaceBefore=6, spaceAfter=4))

    # fill-in header row
    E.append(Table([["Bumper #:", "", "Vehicle:", "", "Mechanic:", "", "WO #:", ""]],
                   colWidths=[0.7 * inch, 1.0 * inch, 0.6 * inch, 1.0 * inch, 0.7 * inch, 1.0 * inch, 0.5 * inch, 0.9 * inch]))
    E[-1].setStyle(TableStyle([("FONTSIZE", (0, 0), (-1, -1), 8), ("LINEBELOW", (1, 0), (1, 0), 0.5, colors.grey),
                               ("LINEBELOW", (3, 0), (3, 0), 0.5, colors.grey), ("LINEBELOW", (5, 0), (5, 0), 0.5, colors.grey),
                               ("LINEBELOW", (7, 0), (7, 0), 0.5, colors.grey), ("BOTTOMPADDING", (0, 0), (-1, -1), 6)]))

    # supersession / interchangeability warnings
    sup = pkg.get("supersession") or {}
    ver = pkg.get("verdict") or {}
    warns = []
    if sup.get("status") == "obsolete/terminal":
        rb = (", replaced by " + ", ".join(sup.get("replaced_by") or [])) if sup.get("replaced_by") else ""
        warns.append("OBSOLETE / TERMINAL NSN%s (AAC: %s). Confirm the current stock number before ordering." %
                     (rb, _esc(sup.get("aac_meaning") or "?")))
    if ver.get("label"):
        warns.append("Interchangeability: %s -- %s" % (_esc(ver.get("label")), _esc(ver.get("reason") or "")))
    if warns:
        E.append(Paragraph("Alerts", ss["H"]))
        for w in warns:
            E.append(Paragraph("&#9888; " + w, ss["Warn"]))

    # parts to order
    parts = pkg.get("parts") or []
    if parts:
        E.append(Paragraph("Part to order &mdash; confirm the right NSN for THIS vehicle", ss["H"]))
        data = [["NSN", "UOC", "CAGEC", "Note", "✓"]]
        for p in parts[:8]:
            data.append([_esc(p.get("nsn")), _esc(p.get("uoc")), _esc(p.get("cagec")), _esc(p.get("note")), ""])
        tb = Table(data, colWidths=[1.5 * inch, 1.1 * inch, 0.9 * inch, 2.3 * inch, 0.3 * inch])
        tb.setStyle(TableStyle([("FONTSIZE", (0, 0), (-1, -1), 8.5), ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef6")),
                                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c8d2de")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        E.append(tb)

    # key dimensions
    dims = pkg.get("dims") or []
    if dims:
        E.append(Paragraph("Key dimensions &amp; specs (consolidated)", ss["H"]))
        data = [["Dimension", "Value", "Source"]]
        for d in dims[:14]:
            data.append([_esc(d.get("type")), _esc("%s %s" % (d.get("value", ""), d.get("unit", ""))).strip(),
                         _esc(d.get("source") or ("manual" if d.get("authoritative") else "external"))])
        tb = Table(data, colWidths=[2.2 * inch, 2.0 * inch, 1.9 * inch])
        tb.setStyle(TableStyle([("FONTSIZE", (0, 0), (-1, -1), 8.5), ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef6")),
                                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c8d2de"))]))
        E.append(tb)

    # torque
    tq = pkg.get("torque") or []
    if tq:
        E.append(Paragraph("Torque values (cited)", ss["H"]))
        for s in tq[:10]:
            E.append(Paragraph("<b>%s</b> &mdash; %s <font size=7 color='#666'>(p.%s)</font>" %
                               (_esc(s.get("value")), _esc(s.get("context")), _esc(s.get("page"))), ss["Body"]))

    # procedures
    procs = pkg.get("procedures") or []
    if procs:
        E.append(Paragraph("Procedure", ss["H"]))
        for p in procs[:4]:
            hdr = "%s" % _esc(p.get("kind") or "Procedure")
            cite = " ".join(x for x in [_esc(p.get("vehicle") or p.get("tm_number") or ""),
                                        ("p." + _esc(p.get("page"))) if p.get("page") else ""] if x)
            E.append(Paragraph("<b>%s</b>  <font size=7 color='#666'>%s</font>" % (hdr, cite), ss["Body"]))
            for c in (p.get("cautions") or [])[:4]:
                E.append(Paragraph("&#9888; <b>%s</b> &mdash; %s" % (_esc(c.get("kind")), _esc(c.get("text"))), ss["Warn"]))
            if p.get("tools"):
                E.append(Paragraph("<b>Tools:</b> " + _esc(", ".join(p["tools"][:20])), ss["Small"]))
            steps = p.get("steps") or []
            if steps:
                E.append(ListFlowable([ListItem(Paragraph(_esc(s), ss["Body"]), leftIndent=12) for s in steps[:40]],
                                      bulletType="1", start="1"))
    if not (parts or dims or tq or procs):
        E.append(Paragraph("No structured procedure/parts data available yet (coverage grows as OCR completes). "
                           "Open the cited catalog page on the device.", ss["Body"]))

    E.append(Spacer(1, 8))
    E.append(HRFlowable(width="100%", color=colors.HexColor("#c8d2de"), spaceBefore=4, spaceAfter=3))
    E.append(Paragraph("This package is a convenience aid assembled from the cited technical manuals and the DLA "
                       "federal catalog (PUBLOG). <b>Verify every torque value, sequence, and CAUTION/WARNING against "
                       "the actual TM page before working.</b>", ss["Small"]))
    doc.build(E)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# self-test: `python jobpack.py`                                              #
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    import sys
    if not available():
        print("jobpack self-test SKIPPED (reportlab not installed)"); sys.exit(0)
    pkg = {
        "title": "ALTERNATOR", "nsn": "2920-01-234-5678", "fsc_title": "GENERATORS AND GENERATOR SETS",
        "verdict": {"label": "One-way substitute (supersession)", "reason": "NSN X replaces this in that direction only."},
        "supersession": {"status": "obsolete/terminal", "aac_meaning": "terminal item", "replaced_by": ["012345678"]},
        "parts": [{"nsn": "2920-01-234-5678", "uoc": "ABC", "cagec": "19207", "note": "primary"}],
        "dims": [{"type": "output voltage", "value": "28", "unit": "V", "authoritative": True},
                 {"type": "length", "value": "7.5", "unit": "in", "source": "manual"}],
        "torque": [{"value": "35 ft-lb", "context": "mounting bolts", "page": "4-12"}],
        "cautions": [{"kind": "WARNING", "text": "Disconnect the battery ground first."}],
        "procedures": [{"kind": "REMOVE", "vehicle": "HMMWV", "page": "4-12",
                        "cautions": [{"kind": "CAUTION", "text": "Support the unit before removing the last bolt."}],
                        "tools": ["1/2in socket", "torque wrench"], "steps": ["Disconnect leads.", "Remove 3 bolts.", "Lift out."]}],
        "generated": "2026-07-02",
    }
    pdf = build(pkg)
    assert pdf[:5] == b"%PDF-", "not a PDF"
    assert len(pdf) > 2000, "PDF too small"
    print("jobpack self-test OK  (valid %d-byte PDF, all sections)" % len(pdf))

# END OF FILE
